when operator collection does not exists in workspace
IBM/operator-collection-sdk-vscode-extension pull request #123
Opened 2023-11-07 16:19 UTC by MariandreaMV

2023-11-08 04:19 UTC, freemanlatrell requested changes
@MariandreaMV Can the dropdown below be updated to use the `select` dropdown, giving the user only the `Yes` or `No` options to select. Here's an example https://github.com/IBM/operator-collection-sdk-vscode-extension/blob/main/src/utilities/util.ts#L245-L250
![image](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/24191850/0c499092-13e6-46fd-acf7-16ae1b7f0498)

2023-11-08 04:29 UTC, freemanlatrell requested changes
Also, how are you determining which directory to store the new initialized collection? When testing in a new VS Code window, it seems to be attempting to store this collection in my root directory....which causes the failure below:

```
TASK [Initialize collection] ***************************************************

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["ansible-galaxy", "collection", "init", "undefined.racf_operator", "--init-path", "/"], "delta": "0:00:00.191989", "end": "2023-11-07 23:24:52.087264", "msg": "non-zero return code", "rc": 250, "start": "2023-11-07 23:24:51.895275", "stderr": "ERROR! Unexpected Exception, this is probably a bug: [Errno 30] Read-only file system: b'/undefined'", "stderr_lines": ["ERROR! Unexpected Exception, this is probably a bug: [Errno 30] Read-only file system: b'/undefined'"], "stdout": "to see the full traceback, use -vvv", "stdout_lines": ["to see the full traceback, use -vvv"]}
...ignoring

TASK [Create playbooks directory] **********************************************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an issue creating /undefined as requested: [Errno 30] Read-only file system: b'/undefined'", "path": "//undefined/racf_operator/playbooks/roles"}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=1   
```

2023-11-08 04:29 UTC, freemanlatrell commented on package.json
> +        "contents": "Operator Collection isn’t detected in current workspace \n[Initialize Operator Collection](command:operator-collection-sdk.initCollection)\n[skip](command:operator-collection-sdk
```suggestion
        "contents": "Operator Collection isn’t detected in current workspace \n[Initialize Operator Collection](command:operator-collection-sdk.initCollection)\n[Skip](command:operator-collection-sdk.initCollectionSkip)",
```

2023-11-08 04:29 UTC, freemanlatrell commented on src/utilities/util.ts
> +
You should add validation check here to determine if the `ansibleGalaxyNamespace` is either `undefined` (meaning a user pressed Escape to cancel the prompts), or an empty string (meaning the user didn't specify the require value)

2023-11-08 04:29 UTC, freemanlatrell commented on src/utilities/util.ts
> +
Same validation here

2023-11-08 21:23 UTC, MariandreaMV commented
when opening a new window there is not folder opened, now It will prompt the user to open a new one as the following screenshot.
![Screenshot 2023-11-08 at 4 17 43 PM](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/23127680/40a18333-839f-47d4-bfbc-266974d3649d)

and if the folder doesn’t have a collection it will looks like this: 

![Screenshot 2023-11-08 at 4 22 50 PM](https://github.com/IBM/operator-collection-sdk-vscode-extension/assets/23127680/a2b1ad8e-7885-4a2a-959f-fb798517cf0e)

2023-11-17 21:06 UTC, freemanlatrell approved these changes

2023-11-17 21:06 UTC, merged